apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: guestbook-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "frontend"
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: External
    external:
      metricName: citrixadc_http_requests_rate
      targetAverageValue: 20
